---
title: 'Analyses: Analyses for paper: Social-relational classroom climate and its link to primary students’ behavioral problems'
author: "Jürgen Wilbert"
date: "Version (`r Sys.Date()`)"
output:
  html_document:
    theme: cosmo
    df_print: paged
    toc: yes
    toc_depth: 2
    toc_float:
      collapsed: no
bibliography: packages.bib
geometry: a4paper
csl: apa.csl
link-citations: yes
biblio-style: apalike
---

```{r setup, include=FALSE}
# load packages -----------------------------------------------------------

if (!("wmisc" %in% installed.packages())) 
  devtools::install_github("jazznbass/wmisc")
if (!("scaledic" %in% installed.packages())) 
  devtools::install_github("jazznbass/scaledic")

packages <- c(
  'sjPlot', 'knitr', 'semTable', 'kableExtra', 'bookdown', 
  'scaledic', 'Amelia', 'wmisc', 'psych', 'lavaan', 'nlme', 'lme4',
  'tidyverse', 'readxl', 'gridExtra', 'broom', 'sjPlot', 'mclust', 'huxtable'
)

invisible(sapply(packages, library, character.only = TRUE))

# load data

dat <- readRDS("data_l1.rds")
dat_agg <- readRDS("data_l2.rds")
dat_teachers <- readRDS("data_teachers.rds")
dat_alpha <- readRDS("data_alpha.rds")

# Define variables: classclimate/wellbeing/behavioral problems/control for all analyzes
var_cc_l1 <- c("feess_ga", "feess_si", "soc_relatedness","soc_positivity", "sar_victim", "sar_perpetrator")
var_cc_l2 <- paste0(var_cc_l1, "_mean")
var_cc_l2_sd <- paste0(var_cc_l1, "_sd")

var_bp_l1 <- c("itrf_sw", "itrf_ad", "itrf_apd", "itrf_opp")
var_bp_l2 <- paste0(var_bp_l1, "_mean")
var_bp_l2_sd <- paste0(var_bp_l1, "_sd")

var_cont_l1 <- c("age", "grade", "sex", "migration_background")
var_cont_l2 <- paste0(var_cont_l1, "_mean")
var_cont_l2_sd <- paste0(var_cont_l1, "_sd")

# set parameters

knitr::opts_chunk$set(echo = FALSE, warning = FALSE)

# function for nicer output
html_table <- function(table, title = "", footnote = "") {
  title <- paste0("Table.<br><i>", title, "</i>")
  kable(table, caption = title) %>%
   kable_classic(full_width = FALSE) %>%
   footnote(footnote)
}

html_regression <- function(fit, ...) {
  sjPlot::tab_model(fit, ..., show.est = FALSE, show.std = TRUE, show.se = TRUE, show.ci = FALSE, string.est = "B", string.std = "Beta", string.se = "SE B", string.std_se = "SE")#, p.style = "stars") 
}

poly_table <- function(x, caption = "", footnote = "", header = "", width = 1, ...) {
  
  x <- as_hux(x) %>%
    theme_article %>%
    set_caption(caption) 
  
  if (!identical(header, "")) {
      cols <- rep(" ", length(unlist(header)))
      for(i in seq_along(header)) cols[min(unlist(header[i]))] <- names(header)[i]
      x <- do.call(insert_row, c(list(ht = x, after = 0), as.list(cols)))
      for(i in seq_along(header)) {
        x <- do.call(merge_cells, list(x, row = 1, col = header[[i]]))
      }
      x <- x %>%
        set_align(1:2, everywhere, "center") %>% 
        set_tb_padding(1, everywhere, 0) %>% 
        set_bold(1, everywhere) %>%
        set_width(1)
  }
  
  if (!is.null(width)) x <- set_width(x, width)
  if (footnote != "") x <- add_footnote(x, footnote, italic = TRUE)
  
  x  
}
```

# Software acknowledgment

The following packages were used for this report:

`R` at version `r R.version$version.string` [@R-base].

```{r package_reference, results="asis", echo=FALSE}
wmisc::reference_package_version(packages)
```

------------------------------------------------------------------------

# Material

```{r alpha}
  dat_alpha %>% html_table("Item Analyzes with the data of the present study.")
```

# Descriptives of all variables

```{r teachers_sample}
  dat_teachers %>% t() %>% html_table(title = "Teacher sample", footnote = "Age and active years as a teacher were administered as categorical variables (age: 20-30; 31-40, 41-50, 51-60, > 60; active years: < 1, 1-3, 4-10, > 10)")
```

```{r descriptives_l1}
.var <- c(var_cc_l1, var_bp_l1, "age", "sex_male", "migration_background_numeric")

dat %>% select(!!.var) %>% rename_items() %>% descriptives() %>% html_table

dat %>% group_by(grade) %>% summarise(n = n()) %>% html_table
dat %>% group_by(sex) %>% summarise(n = n()) %>% html_table
dat %>% group_by(migration_background) %>% summarise(n = n()) %>% html_table

dat %>% select(!!.var) %>% rename_items() %>% wmisc::nice_corrmatrix(upper = FALSE, numbered_columns = TRUE, char_p10 = "T") %>% html_table
```

```{r descriptives_l2}
.var <- c(var_cc_l2, var_bp_l2, "age_mean", "sex_male_mean", "migration_background_numeric_mean")
dat_agg %>% 
  select(!!.var) %>% 
  rename_items() %>% 
  descriptives() %>% 
  html_table()

dat_agg %>% 
  select(!!.var) %>% rename_items() %>% 
  wmisc::nice_corrmatrix(upper = FALSE, numbered_columns = TRUE, char_p10 = "T") %>% html_table
```

# Exploratory factor analses

```{r parallel_l1, fig.cap="Parallel analysis scree plot."}
dat %>% select(!!var_cc_l1) %>% fa.parallel(main = "", fa = "fa")
```

```{r efa_l1}
dat %>% 
  select(!!var_cc_l1) %>% 
  rename_items() %>% 
  exploratory_fa(nfactors = 2, cut = 0.2, fm = "minres") %>% 
  html_table("Exploratory factor analyzes of social relation variables.")
```

```{r nfactors_l2, , fig.cap="Parallel analysis scree plot."}
dat_agg %>% 
  select(!!var_cc_l2) %>% 
  fa.parallel(main = "", fa = "fa")
```

```{r efa_l2}
dat_agg %>% 
  select(!!var_cc_l2) %>% 
  rename_items() %>% 
  exploratory_fa(nfactors = 2, fm = "minres") %>%
  html_table("Exploratory factor analyzes of mean social relation variables.")
```

# Multilevel regression analyses

```{r}
dat_l12 <- full_join(dat, dat_agg, by = "id_class_teacher")
```

```{r}
fit_l1 <- lme(itrf_sw ~ feess_si + feess_ga + soc_relatedness + soc_positivity + sar_victim + sar_perpetrator + migration_background + age + sex, random =~ 1 | id_class_teacher, data = dat_l12, na.action = na.omit)

fit_l2 <- update(fit_l1, .~. +feess_si_mean + feess_ga_mean + soc_relatedness_mean + soc_positivity_mean + sar_victim_mean + sar_perpetrator_mean + age_mean + migration_background_numeric_mean + sex_male_mean)

fit_mean <- lme(itrf_sw ~ feess_si_mean + feess_ga_mean + soc_positivity_mean + soc_relatedness_mean   + sar_victim_mean + sar_perpetrator_mean + age_mean + migration_background_numeric_mean + sex_male_mean, random = ~  1|id_class_teacher, data = dat_l12, na.action = na.omit)

html_regression(fit_l1, fit_l2, fit_mean, title = "Social withdrawal regressed on individual social-relations and social-relational classclimate", dv.labels = c("Model 1 (L1)", "Model 2 (L1+L2)", "Model 3 (mean-as-outcome)"))
```

```{r}
fit_l1 <- lme(itrf_ad ~ feess_si + feess_ga + soc_relatedness + soc_positivity + sar_victim + sar_perpetrator + migration_background + age + sex, random =~ 1 | id_class_teacher, data = dat_l12, na.action = na.omit)

fit_l2 <- update(fit_l1, .~. +feess_si_mean + feess_ga_mean + soc_relatedness_mean + soc_positivity_mean + sar_victim_mean + sar_perpetrator_mean + age_mean + migration_background_numeric_mean + sex_male_mean)

fit_mean <- lme(itrf_ad ~ feess_si_mean + feess_ga_mean + soc_positivity_mean + soc_relatedness_mean + sar_victim_mean + sar_perpetrator_mean + age_mean + migration_background_numeric_mean + sex_male_mean, random = ~  1|id_class_teacher, data = dat_l12, na.action = na.omit)

html_regression(fit_l1, fit_l2, fit_mean, title = "Anxiety/depression regressed on individual social-relations and social-relational classclimate", dv.labels = c("Model 1 (L1)", "Model 2 (L1+L2)", "Model 3 (mean-as-outcome)"))

```

```{r}
fit_l1 <- lme(itrf_apd ~ feess_si + feess_ga + soc_relatedness + soc_positivity + sar_victim + sar_perpetrator + migration_background + age + sex, random =~ 1 | id_class_teacher, data = dat_l12, na.action = na.omit)

fit_l2 <- update(fit_l1, .~. +feess_si_mean + feess_ga_mean + soc_relatedness_mean + soc_positivity_mean + sar_victim_mean + sar_perpetrator_mean + age_mean + migration_background_numeric_mean + sex_male_mean)

fit_mean <- lme(itrf_apd ~ feess_si_mean + feess_ga_mean + soc_positivity_mean + soc_relatedness_mean   + sar_victim_mean + sar_perpetrator_mean + age_mean + migration_background_numeric_mean + sex_male_mean, random = ~  1|id_class_teacher, data = dat_l12, na.action = na.omit)

html_regression(fit_l1, fit_l2, fit_mean, title = "Academic disorganized behavior regressed on individual social-relations and social-relational classclimate", dv.labels = c("Model 1 (L1)", "Model 2 (L1+L2)", "Model 3 (mean-as-outcome)"))

```

```{r}
fit_l1 <- lme(itrf_opp ~ feess_si + feess_ga + soc_relatedness + soc_positivity + sar_victim + sar_perpetrator + migration_background + age + sex, random =~ 1 | id_class_teacher, data = dat_l12, na.action = na.omit)

fit_l2 <- update(fit_l1, .~. +feess_si_mean + feess_ga_mean + soc_relatedness_mean + soc_positivity_mean + sar_victim_mean + sar_perpetrator_mean + age_mean + migration_background_numeric_mean + sex_male_mean)

fit_mean <- lme(itrf_opp ~ feess_si_mean + feess_ga_mean + soc_positivity_mean + soc_relatedness_mean   + sar_victim_mean + sar_perpetrator_mean + age_mean + migration_background_numeric_mean + sex_male_mean, random = ~  1|id_class_teacher, data = dat_l12, na.action = na.omit)

html_regression(fit_l1, fit_l2, fit_mean, title = "Oppositional behavior regressed on individual social-relations and social-relational classclimate", dv.labels = c("Model 1 (L1)", "Model 2 (L1+L2)", "Model 3 (mean-as-outcome)"))

```

# Reference
